### PR TITLE
Fix whitespace issues around top-level expression and within function…

### PR DESCRIPTION
**Pull request by dsyrstad**
… call arguments. Fixes both issues in #19.

### CODE REVIEW

**Comment by dsyrstad** [comment]
@rbellens @shyndman Can we merge this PR?

**Comment by rbellens** [comment]
@dsyrstad I'll have a look

**Comment by dsyrstad** [comment]
@rbellens Have you had a chance to look yet? I think it's pretty straightforward.

**Comment by rbellens** [comment]
Sorry for the delay. Will release soon.

**Comment by dsyrstad** [comment]
@rbellens Thank you!!

**Pull request merged**
